[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/cv"
  to = "/pages/cv.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "https://www.notion.so/nibru/f3af003e382f4615adb73c8ff5a24ff5?v=78ec0e736948471a9417c21daf6e19c2"
  status = 301
  force = true

[[redirects]]
  from = "/photography"
  to = "/pages/photography.html"
  status = 200
  force = true

[[redirects]]
  from = "/music"
  to = "/pages/music.html"
  status = 200
  force = true

[[redirects]]
  from = "/legal"
  to = "/pages/legal.html"
  status = 200
  force = true

